name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # workflow_dispatch:
  #   branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 16.13.1
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
      - name: Build
        run: npm ci && npm install && npm run ng-high-memory -- b --configuration production
